from tkinter import*
import calendar
gui = Tk()
gui.config(background="medium spring green")
gui.title("CALENDER")
gui.geometry("250x140")
def submit_year():
    gui2 = Tk()
    gui2.config(background="medium spring green")
    gui2.title("CALENDER")
    gui2.geometry("250x140")
    choice = year.get() 
    choice = int(choice)
    cal_content = calendar.calendar(choice)
    title3 = Label (gui2, text = cal_content,fg = "red3" ,bg="medium spring green", font = ( "times",13,"bold")) 
    title3.place(x = 100 , y = 100)
    gui2.mainloop()

title1 = Label (gui, text = "CALENDAR",fg = "red3" ,bg="medium spring green", font = ( "times",28,"bold")) 
title1.place(x = 50 , y = 50)
title2 = Label (gui, text = "Enter the year",fg = "red3" ,bg="medium spring green", font = ( "times",28,"bold")) 
title2.place(x = 100 , y = 100)
year = Entry ()
year.place(x = 200, y = 180)
submit = Button (gui,text ="submit",bg = "red3", fg = "medium spring green", command = submit_year)
submit.place(x = 150, y = 250)
close = Button (gui,text ="close",bg = "red3", fg = "medium spring green", command = exit)
close.place(x = 300, y = 250)
gui.mainloop()
