from tkinter import*
gui = Tk()
gui.config(background="gold")
gui.title("GAME")
gui.geometry("250x140")

title1 = Label (gui, text = "Rock Paper Scissors ",fg = "SpringGreen2" ,bg="gray99", font = ( "times",28,"bold")) 
title1.place(x = 90 , y = 50)
title2 = Label (gui, text = "Let's start the Game",fg = "SpringGreen2" ,bg="gray99", font = ( "times",28,"bold")) 
title2.place(x = 210 , y = 100)
title3 = Label (gui, text = "Your Options",fg = "SpringGreen2" ,bg="gray99", font = ( "times",25,"bold")) 
title3.place(x = 100 , y = 200)

Rock = Button (gui,text ="Rock", width = 15 ,bg = "gray99", fg = "SpringGreen2")
Rock.place(x = 250, y = 250)
Paper = Button (gui,text ="Paper", width = 15 ,bg = "gray99", fg = "SpringGreen2")
Paper.place(x = 350, y = 250)
Scissors  = Button (gui,text ="Scissors ", width = 15 ,bg = "gray99", fg = "SpringGreen2")
Scissors.place(x = 450, y = 250)

title4 = Label (gui, text = "Score",fg = "SpringGreen2" ,bg="gray99", font = ( "times",25,"bold")) 
title4.place(x = 100 , y = 250)  
computer = Label (gui, text = "Computer Score",fg = "SpringGreen2" ,bg="gray99", font = ( "times",25,"bold")) 
computer.place(x = 200 , y = 280)  
computerselect = Label (gui, text = "Computer Selected:---",fg = "SpringGreen2" ,bg="gray99", font = ( "times",25,"bold")) 
computerselect.place(x = 600 , y = 280)
player = Label (gui, text = "Player Score",fg = "SpringGreen2" ,bg="gray99", font = ( "times",25,"bold")) 
player.place(x = 200 , y = 380)    
playerselect = Label (gui, text = "Your Selected:---",fg = "SpringGreen2" ,bg="gray99", font = ( "times",25,"bold")) 
playerselect.place(x = 600 , y = 380)  
gui.mainloop()
